version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python manage.py runserver 0.0.0.0:9000"
    environment:
      - ENVIRONMENT=production
      - SECRET_KEY=$_f#u(g2!@b68bhqxb@$v=^y2xfc-b)o7_%e)8t#_1_nd9kgty
      - DEBUG=0
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_utDn0dhH2rq0JI7g1AnIQ50X00MvVnMlQN
      - STRIPE_TEST_SECRET_KEY=sk_test_0jEBLGu1gStnW5frFcfcqFJY00Qj336dez
    volumes:
      - .:/code
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: postgres



