# pull base image
FROM python:3.8.2

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# set work dir
RUN mkdir /code/
WORKDIR /code/
COPY . /code/

# install requirements
RUN pip install -r requirements.txt

